'use strict';
// Declare app level module which depends on views, and components

angular.module('app', [
    'ngRoute',
    'app.tile',
    'app.home',
    'app.rooms',
    'app.scenarios',
    'app.rules',
    'app.weather',
    'app.settings',
    'app.navigation',
    'app.header',
    'ngMaterial'
])

    .config(['$routeProvider', function ($routeProvider) {
        $routeProvider.otherwise({redirectTo: '/home'});
    }])

    .config(['$mdIconProvider', function ($mdIconProvider) {

        $mdIconProvider.icon('alarm', 'img/icons/Alarm.svg')
            .icon('alarm_on', 'img/icons/Alarm_On.svg')
            .icon('addfunc', 'img/icons/addfunc.svg')
            .icon('babymonitor', 'img/icons/BabyMonitor.svg')
            .icon('babymonitor_on', 'img/icons/BabyMonitor_On.svg')
            .icon('bathtub', 'img/icons/Bathtub.svg')
            .icon('bathtub_on', 'img/icons/Bathtub_On.svg')
            .icon('beamer_on', 'img/icons/Beamer_On.svg')
            .icon('beamer', 'img/icons/Beamer.svg')
            .icon('bookmark', 'img/icons/Bookmark.svg')
            .icon('bookmarked', 'img/icons/Bookmarked.svg')
            .icon('bulb_no_light', 'img/icons/Bulb_No_Light.svg')
            .icon('bulb_with_light', 'img/icons/Bulb_With_Light.svg')
            .icon('camera', 'img/icons/Camera.svg')
            .icon('camera_on', 'img/icons/Camera_On.svg')
            .icon('camera_digi', 'img/icons/Camera_Digi.svg')
            .icon('coffeemaker', 'img/icons/CoffeeMaker.svg')
            .icon('collapse', 'img/icons/collapse.svg')
            .icon('condition', 'img/icons/Condition.svg')
            .icon('confirm', 'img/icons/Confirm.svg')
            .icon('delete', 'img/icons/Delete.svg')
            .icon('door', 'img/icons/Door.svg')
            .icon('door_locked', 'img/icons/Door_Locked.svg')
            .icon('door_unlocked', 'img/icons/Door_Unlocked.svg')
            .icon('edit', 'img/icons/Edit.svg')
            .icon('energy_1', 'img/icons/Energy_1.svg')
            .icon('energy_2', 'img/icons/Energy_2.svg')
            .icon('entrances', 'img/icons/Entrances.svg')
            .icon('expand', 'img/icons/expand.svg')
            .icon('favorite', 'img/icons/favorite.svg')
            .icon('forward', 'img/icons/Forward.svg')
            .icon('frame_off', 'img/icons/Frame_Off.svg')
            .icon('frame_on_alt', 'img/icons/Frame_On_Alt.svg')
            .icon('frame_on', 'img/icons/Frame_On.svg')
            .icon('fridge', 'img/icons/Fridge.svg')
            .icon('hallway', 'img/icons/Hallway.svg')
            .icon('headphones', 'img/icons/Headphones.svg')
            .icon('heating', 'img/icons/Heating.svg')
            .icon('information', 'img/icons/Information.svg')
            .icon('lawnmower', 'img/icons/LawnMower.svg')
            .icon('lawnmower_on', 'img/icons/LawnMower_On.svg')
            .icon('lock_closed', 'img/icons/Lock_Closed.svg')
            .icon('lock_open', 'img/icons/Lock_Open.svg')
            .icon('marquee', 'img/icons/Marquee.svg')
            .icon('marquee_out', 'img/icons/Marquee_Out.svg')
            .icon('motiondetector', 'img/icons/MotionDetector.svg')
            .icon('motiondetector_on', 'img/icons/MotionDetector_On.svg')
            .icon('mp_bwd', 'img/icons/mp_bwd.svg')
            .icon('mp_fbwd', 'img/icons/mp_fbwd.svg')
            .icon('mp_ffwd', 'img/icons/mp_ffwd.svg')
            .icon('mp_fwd', 'img/icons/mp_fwd.svg')
            .icon('mp_pause', 'img/icons/mp_pause.svg')
            .icon('mp_play', 'img/icons/mp_play.svg')
            .icon('mp_stop', 'img/icons/mp_stop.svg')
            .icon('music', 'img/icons/Music.svg')
            .icon('add', 'img/icons/m_emergency.svg')
            .icon('m_emergency', 'img/icons/m_emergency.svg')
            .icon('m_energy', 'img/icons/m_energy.svg')
            .icon('m_headphones', 'img/icons/m_headphones.svg')
            .icon('m_home', 'img/icons/m_home.svg')
            .icon('m_less', 'img/icons/m_less.svg')
            .icon('m_more', 'img/icons/m_more.svg')
            .icon('m_options', 'img/icons/m_options.svg')
            .icon('m_rooms', 'img/icons/m_rooms.svg')
            .icon('m_rules', 'img/icons/m_rules.svg')
            .icon('m_scenario', 'img/icons/m_scenario.svg')
            .icon('m_security', 'img/icons/m_security.svg')
            .icon('m_weather', 'img/icons/m_weather.svg')
            .icon('pool', 'img/icons/Pool.svg')
            .icon('pool_closed', 'img/icons/Pool_Closed.svg')
            .icon('rollo', 'img/icons/Rollo.svg')
            .icon('r_basement', 'img/icons/r_basement.svg')
            .icon('r_bathroom', 'img/icons/r_bathroom.svg')
            .icon('r_bedroom', 'img/icons/r_bedroom.svg')
            .icon('r_child_bedroom', 'img/icons/r_child_bedroom.svg')
            .icon('r_garden', 'img/icons/r_garden.svg')
            .icon('r_kitchen', 'img/icons/r_kitchen.svg')
            .icon('r_livingroom', 'img/icons/r_livingroom.svg')
            .icon('scenario', 'img/icons/Scenario.svg')
            .icon('screen_collapsed', 'img/icons/Screen_Collapsed.svg')
            .icon('screen', 'img/icons/Screen.svg')
            .icon('security', 'img/icons/Security.svg')
            .icon('smarthome', 'img/icons/SmartHome.svg')
            .icon('socket', 'img/icons/Socket.svg')
            .icon('speaker_on', 'img/icons/Speaker_On.svg')
            .icon('speaker', 'img/icons/Speaker.svg')
            .icon('star', 'img/icons/star.svg')
            .icon('starred', 'img/icons/starred.svg')
            .icon('stove_on', 'img/icons/Stove_On.svg')
            .icon('stove', 'img/icons/Stove.svg')
            .icon('temperature', 'img/icons/Temperature.svg')
            .icon('tv', 'img/icons/TV.svg')
            .icon('tv_on', 'img/icons/TV_On.svg')
            .icon('washingmachine', 'img/icons/WashingMachine.svg')
            .icon('washingmachine_on', 'img/icons/WashingMachine_On.svg')
            .icon('waterdrop', 'img/icons/WaterDrop.svg')
            .icon('watering', 'img/icons/Watering.svg')
            .icon('watering_on', 'img/icons/Watering_On.svg')
            .icon('weather', 'img/icons/Weather.svg')
            .icon('window_1', 'img/icons/Window_1.svg')
            .icon('window_2', 'img/icons/Window_2.svg')
            .icon('window_3_close', 'img/icons/Window_3_close.svg')
            .icon('window_3_open', 'img/icons/Window_3_open.svg')
            .icon('w_clear_night', 'img/icons/w_clear_night.svg')
            .icon('w_cloudy', 'img/icons/w_cloudy.svg')
            .icon('w_partly_cloudy', 'img/icons/w_partly_cloudy.svg')
            .icon('w_partly_cloudy_night', 'img/icons/w_partly_cloudy_night.svg')
            .icon('w_rainy', 'img/icons/w_rainy.svg')
            .icon('w_stormy', 'img/icons/w_stormy.svg')
            .icon('w_sunny', 'img/icons/w_sunny.svg');
    }]);
